### ISSUE TITLE
PHP7 compatibility -- INI directive 'magic_quotes_runtime' is deprecated since PHP 5.3 and removed since PHP 5.4.

### ISSUE THREAD

**Issue by hogash** [jbrooksuk/MCAPI-PHP#5]
Hey there!

Is this project still maintained? After a PHP7 compatibility test we got this into our report:

```
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------
 2884 | WARNING | INI directive 'magic_quotes_runtime' is deprecated since PHP 5.3 and removed since PHP 5.4.
------------------------------------------------------------------------------------------------------------------
```

Solution as per http://stackoverflow.com/a/2218021/1134145 by using http://php.net/manual/en/function.get-magic-quotes-runtime.php .

Would this be ok?

**Comment by jbrooksuk** [comment]
> Is this project still maintained? After a PHP7 compatibility test we got this into our report:

Not really, I'd check out https://github.com/BlueBayTravel/Mailchimp
